### ISSUE TITLE
add sync action demo

### ISSUE THREAD

**Issue by Halama** [keboola/docker-demo-app#1]
Hodilo by se mi pro otestování https://github.com/keboola/syrup-router/issues/51 
A zároveň by imho mohlo pomoct i pro inspiraci.
Klidně to udělám pokud @ondrejhlavacek nebude proti téhle úpravě.

**Comment by ondrejhlavacek** [comment]
pro integrační testování sync akcí používáme komponentu `testing.dca-custom-science-actions`. je to vidět tady https://jenkins.keboola.com/user/ondra/my-views/view/%C5%A0ajzekace/job/Testing%20-%20docker-bundle/configure a stačilo by to imho otestovat na ní.

**Comment by Halama** [comment]
aha, ale tu appku `testing.dca-custom-science-actions` nevidim v dev-portalu a taky pouziva quay a ne ECR.

**Comment by ondrejhlavacek** [comment]
No jasně, na ECR by se právě přesunula v rámci toho testu, teď by jinak nešlapala :-) No a došlo mi, že se to vlastně pouští na `https://syrup-testing.keboola.com`, tam teď na ECR jede `testing.docker-demo-aws-ecr` a už si sakra vůbec nepamatuju, jak to je nastavený, aby to šlapalo.

**Comment by ondrejhlavacek** [comment]
Na developer portalu jí normálně vidím, pod vendorem `keboola`

![image](https://user-images.githubusercontent.com/497675/26943972-304fdb92-4c3c-11e7-894b-07972ef249f8.png)

**Comment by Halama** [comment]
aha, jasne ona asi neni public proto jsem ji nevidel.

**Comment by Halama** [comment]
takže jí přehodím na ECR přes dev portal

**Comment by Halama** [comment]
to už ale vidím že bych ty testy a vše už musel přesunout na novej syrup testing. OMG, a to vše začalo tím že jsem jenom chtěl spustit syrup za NATem :)

**Comment by ondrejhlavacek** [comment]
Nemohl by tam bejt třeba jenom ten jeden test?

**Comment by Halama** [comment]
tady to zavírám a přesouvám sem https://github.com/keboola/syrup-router/issues/51

**Comment by Halama** [comment]
otevírám znovu. Tamta appka je totiž udělaná jako builder a ten ECR nepodporuje.

**Comment by Halama** [comment]
nakonec jsem to vyřešil takhle https://github.com/keboola/docker-demo-sync-app

**Comment by ondrejhlavacek** [comment]
jo, jasně, ECR to bohužel neumí, fixnout by to asi šlo, ale nebude to úplně triviální. ale stačilo nakonec upravit docker-demo-app, ta se pushuje do víc repos a v builderu použít nějakej non-ECR.

**Comment by ondrejhlavacek** [comment]
asi to příležitostně mergnu, máš ten test někde integrovanej, nebo to byla jednorázovka? přidal bych ho pak sem - https://jenkins.keboola.com/user/ondra/my-views/view/%C5%A0ajzekace/job/Testing%20-%20docker-bundle/configure

**Comment by Halama** [comment]
to se pak pořeší při přenosu buildu docker runneru na travis a deploy na novej testing

**Comment by Halama** [comment]
víc k tomu tady https://github.com/keboola/syrup-router/issues/51
