### ISSUE TITLE
Travis build should use image with baked-in code

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/docker-demo-app#5]
Currently it runs on `dev` service from docker-compose with code linked from host.

**Comment by tomasfejfar** [comment]
`docker-demo-app` je outdated a nahrazeno https://github.com/keboola/component-generator/. Takže zavírám. A ideálně i to repository archivovat, ať se podle něj někdo neřídí, což @odinuv ?

**Comment by odinuv** [comment]
no jeste by se me asi libilo prenest nejak ten @ondrejhlavacek xdebug setup, takze uplne nahrazeny to jeste neni, a taky je to asi odkazovany jeste v dokumentaci
